spring:
  datasource:
    url: jdbc:mysql://localhost:13306/test?useSSL=false&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
    username: test
    password: test123
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: spring-mvc
  output:
    ansi:
      enabled: always
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true

logging:
  level:
    com.fastcampus: debug