spring:
  application:
    name: spring-coroutine-advanced
  output:
    ansi:
      enabled: always
  r2dbc:
    url: r2dbc:pool:mariadb://localhost:23306/test
    username: test
    password: test123
  sql:
    init:
      mode: always
      schema-locations: classpath:db-init/schema.sql
  data:
    redis:
      host: localhost
      port: 6379


server:
  shutdown: graceful
  compression:
    enabled: true
  port: 8080
  error:
    include-exception: on
    include-message: always
    include-stacktrace: always
    include-binding-errors: always


logging:
  level:
    com.fastcampus: debug
    org.springframework.r2dbc.core: debug
    org.springframework.r2dbc.connection.init.ScriptUtils: debug
  pattern:
#    console: "%d{HH:mm:ss.SSS}|%highlight(%-5level)|%X{txid:-}|%green(%t)|%logger|%blue(\\(%F:%L\\))|%msg%n"
    console: "%d{HH:mm:ss.SSS}|%highlight(%-5level)|%X{txid:-}|%green(%t)|%blue(\\(%F:%L\\))|%msg%n"

api:
  external-url: http://localhost:8081

---
spring:
  config:
    activate:
      on-profile: test
  r2dbc:
    url: r2dbc:pool:h2:mem://localhost/test