spring:
  application:
    name: payment
  output:
    ansi:
      enabled: always
  r2dbc:
    url: r2dbc:pool:mariadb://localhost:13306/payment
    username: test
    password: test123
  sql:
    init:
      mode: always
      schema-locations: classpath:db-init/schema.sql
      data-locations: classpath:db-init/test-data.sql
  data:
    redis:
      host: localhost
      port: 6379

logging:
  level:
    com.fastcampus: debug
    org.springframework.r2dbc.core: debug
    org.springframework.r2dbc.connection.init.ScriptUtils: debug
  pattern:
    console: "%d{HH:mm:ss.SSS}|%highlight(%-5level)|%X{txid:-}|%green(%t)|%blue(\\(%F:%L\\))|%msg%n"

server:
  shutdown: graceful
  port: 8080
  error:
    include-message: always
    include-exception: true
    include-stacktrace: always

payment:
  toss:
    client-key: test_ck_QbgMGZzorzbWbaZR12EDrl5E1em4
    secret-key: dGVzdF9za19aTEtHUHg0TTNNYnpFQUJLbmRYZFZCYVd5cHYxOg==

---
spring:
  config:
    activate:
      on-profile: test
  r2dbc:
    url: r2dbc:pool:h2:mem://localhost/payment
  sql:
    init:
      mode: always
      data-locations: ""
